
export ANDROID_HOME=/opt/Android/Sdk
export ANDROID_TOOLS=$ANDROID_HOME/tools
export ANDROID_TOOLS_BIN=$ANDROID_HOME/tools/bin
export ANDROID_PLATFORM_TOOLS=$ANDROID_HOME/platform_tools
export ANDROID_CMDLINE_TOOLS=$ANDROID_HOME/cmdline-tools/latest/bin
export ANDROID_EMULATOR=$ANDROID_HOME/emulator/emulator

export PATH=$PATH:$ANDROID_HOME:$ANDROID_TOOLS:$ANDROID_TOOLS_BIN:$ANDROID_PLATFORM_TOOLS:$ANDROID_CMDLINE_TOOLS:$ANDROID_EMULATOR

